name: Try installing podman
on: [push]
jobs:
  Install-and-check-podman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $GITHUB_WORKSPACE
      - run: ls -la $GITHUB_WORKSPACE
      - run: echo $PWD
      - run: ls -la
      - name: install podman 4
        run: sudo bash $GITHUB_WORKSPACE/scripts/install_podman.sh
      - run: podman --version