name: Try installing podman
on: [push]
jobs:
  Install-and-check-podman:
    runs-on: ubuntu-latest
    steps:
      - name: install podman 4
        run: sudo bash $GITHUB_WORKSPACE/.github/workflows/install_podman.sh
      - run: podman --version