name: Try installing podman
on: [push]
jobs:
  Install-and-check-podman:
    runs-on: ubuntu-latest
    steps:
      - uses: myci-actions/add-deb-repo@latest
        with:
          repo: deb https://deb.debian.org/debian experimental admin main
          repo-name: debian-experimental
          key-asc: keyring.debian.org
          install: podman
      - run: podman --version
            
          
      
