name: Try installing podman
on: [push]
jobs:
  Install-and-check-podman:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository 'deb https://packages.debian.org/ experimental admin'
          sudo apt-get update
          sudo apt-get -y podman
      - run: podman --version
            
          
      
